/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MyComponent {
      'first': string;
      'last': string;
    }
  }

  interface HTMLMyComponentElement extends StencilComponents.MyComponent, HTMLStencilElement {}

  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'my-component': JSXElements.MyComponentAttributes;
    }
  }
  namespace JSXElements {
    export interface MyComponentAttributes extends HTMLAttributes {
      'first'?: string;
      'last'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface FieldCell {
      'index': number;
      'value': number;
    }
  }

  interface HTMLFieldCellElement extends StencilComponents.FieldCell, HTMLStencilElement {}

  var HTMLFieldCellElement: {
    prototype: HTMLFieldCellElement;
    new (): HTMLFieldCellElement;
  };
  interface HTMLElementTagNameMap {
    'field-cell': HTMLFieldCellElement;
  }
  interface ElementTagNameMap {
    'field-cell': HTMLFieldCellElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'field-cell': JSXElements.FieldCellAttributes;
    }
  }
  namespace JSXElements {
    export interface FieldCellAttributes extends HTMLAttributes {
      'index'?: number;
      'onCellClicked'?: (event: CustomEvent) => void;
      'value'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;